In [1]:
#Dependencies
import pandas as pd
import numpy as np
import matplotlib as plt
#import matplotlib.pyplot as plt
import csv
import os

# Reading and merging data sets

In [2]:
#extracting ans reading data from source
mouse_drug_data = pd.read_csv('mouse_drug_data.csv')
clinicaltrial_data = pd.read_csv('clinicaltrial_data.csv')

In [3]:
clinicaltrial_data.head()

  Mouse ID  Timepoint  Tumor Volume (mm3)  Metastatic Sites
0     b128          0                45.0                 0
1     f932          0                45.0                 0
2     g107          0                45.0                 0
3     a457          0                45.0                 0
4     c819          0                45.0                 0

In [4]:
mouse_drug_data.head()

  Mouse ID      Drug
0     f234  Stelasyn
1     x402  Stelasyn
2     a492  Stelasyn
3     w540  Stelasyn
4     v764  Stelasyn

In [5]:
#merging both set of datas together
merged_data = mouse_drug_data.merge(clinicaltrial_data, on="Mouse ID")

In [6]:
merged_data.head()

  Mouse ID      Drug  Timepoint  Tumor Volume (mm3)  Metastatic Sites
0     f234  Stelasyn          0           45.000000                 0
1     f234  Stelasyn          5           47.313491                 0
2     f234  Stelasyn         10           47.904324                 0
3     f234  Stelasyn         15           48.735197                 1
4     f234  Stelasyn         20           51.112713                 2

# Measuring response to Treatement

In [7]:
#tumor val. using drug and timepoint
tumor_vol = merged_data.groupby(['Drug', 'Timepoint']).aggregate({'Tumor Volume (mm3)': 'mean'})

In [8]:
tumor_vol

                     Tumor Volume (mm3)
Drug      Timepoint
Capomulin 0                   45.000000
          5                   44.266086
          10                  43.084291
          15                  42.064317
          20                  40.716325
          25                  39.939528
          30                  38.769339
          35                  37.816839
          40                  36.958001
          45                  36.236114
Ceftamin  0                   45.000000
          5                   46.503051
          10                  48.285125
          15                  50.094055
          20                  52.157049
          25                  54.287674
          30                  56.769517
          35                  58.827548
          40                  61.467895
          45                  64.132421
Infubinol 0                   45.000000
          5                   47.062001
          10                  49.403909
          15                  51.296397
          20                  53.197691
          25                  55.715252
          30                  58.299397
          35                  60.742461
          40                  63.162824
          45                  65.755562
...                                 ...
Ramicane  0                   45.000000
          5                   43.944859
          10                  42.531957
          15                  41.495061
          20                  40.238325
          25                  38.974300
          30                  38.703137
          35                  37.451996
          40                  36.574081
          45                  34.955595
Stelasyn  0                   45.000000
          5                   47.527452
          10                  49.463844
          15                  51.529409
          20                  54.067395
          25                  56.166123
          30                  59.826738
          35                  62.440699
          40                  65.356386
          45                  68.438310
Zoniferol 0                   45.000000
          5                   46.851818
          10                  48.689881
          15                  50.779059
          20                  53.170334
          25                  55.432935
          30                  57.713531
          35                  60.089372
          40                  62.916692
          45                  65.960888

[100 rows x 1 columns]

In [9]:
timepoint_groupby = merged_data.groupby(['Drug','Timepoint'])

In [10]:
#using .sem to get the standard error for the mean at timepoints for 
#each Drug
tumor_Vol_mm3 = timepoint_groupby['Tumor Volume (mm3)'].sem()

tumor_vol_mm3_pd = pd.DataFrame({
    'tumor(Volmm3)' : tumor_Vol_mm3
})

tumor_vol_mm3_pd.head()

                     tumor(Volmm3)
Drug      Timepoint
Capomulin 0               0.000000
          5               0.448593
          10              0.702684
          15              0.838617
          20              0.909731

In [11]:
unpack_tummor_vol = tumor_vol.unstack()

In [12]:
unpack_tummor_vol

          Tumor Volume (mm3)                                              \
Timepoint                 0          5          10         15         20
Drug
Capomulin               45.0  44.266086  43.084291  42.064317  40.716325
Ceftamin                45.0  46.503051  48.285125  50.094055  52.157049
Infubinol               45.0  47.062001  49.403909  51.296397  53.197691
Ketapril                45.0  47.389175  49.582269  52.399974  54.920935
Naftisol                45.0  46.796098  48.694210  50.933018  53.644087
Placebo                 45.0  47.125589  49.423329  51.359742  54.364417
Propriva                45.0  47.248967  49.101541  51.067318  53.346737
Ramicane                45.0  43.944859  42.531957  41.495061  40.238325
Stelasyn                45.0  47.527452  49.463844  51.529409  54.067395
Zoniferol               45.0  46.851818  48.689881  50.779059  53.170334


Timepoint         25         30         35         40         45
Drug
Capomulin  39.939528  38.769339  37.816839  36.958001  36.236114
Ceftamin   54.287674  56.769517  58.827548  61.467895  64.132421
Infubinol  55.715252  58.299397  60.742461  63.162824  65.755562
Ketapril   57.678982  60.994507  63.371686  66.068580  70.662958
Naftisol   56.731968  59.559509  62.685087  65.600754  69.265506
Placebo    57.482574  59.809063  62.420615  65.052675  68.084082
Propriva   55.504138  58.196374  60.350199  63.045537  66.258529
Ramicane   38.974300  38.703137  37.451996  36.574081  34.955595
Stelasyn   56.166123  59.826738  62.440699  65.356386  68.438310
Zoniferol  55.432935  57.713531  60.089372  62.916692  65.960888

In [15]:
x_axis = unpack_tummor_vol.index

#listing medications
medication = ['Capomulin','Infubinol','Ketapril','Placebo']
markers = ['o','o','o','o']
colors = ['black', 'red','green','blue']

# finding y_axis
for x in medication:
    y = medication.index(x)
    plt.errorbar(x_axis, tumor_vol_mm3_pd['tumor(Volmm3)'][x], yerr=tumor_vol_mm3_pd[x], marker=markers[y], color=colors[y], linestyle='--', label=x)
    
    
plt.title('Tumor Response to Treatment')
plt.xlabel('Time (Days)')
plt.ylabel('Tumor Volume (mm3)')
plt.xlim(unpack_tummor_vol.index[0], unpack_tummor_vol.index[-1])
plt.legend(frameon=True, edgecolor="black")
plt.show()

AttributeError: module 'matplotlib' has no attribute 'errorbar'